<?php
// Generates database/seed.sql from database/data/*.json
// (countries, US states, starter cities, popular flags, categories).
// Usage: php scripts/generate_seed.php

$dataDir = __DIR__ . '/../database/data';
$geo     = json_decode(file_get_contents("$dataDir/geo.json"), true);
$cities  = json_decode(file_get_contents("$dataDir/cities.json"), true);
$popular = json_decode(file_get_contents("$dataDir/popular.json"), true);
$popEng  = json_decode(file_get_contents("$dataDir/popular_english.json"), true);

function slugify(string $s): string
{
    $s = strtolower(trim($s));
    $t = @iconv('UTF-8', 'ASCII//TRANSLIT//IGNORE', $s);
    if ($t !== false) $s = $t;
    $s = preg_replace('/[^a-z0-9]+/', '-', $s);
    return trim($s, '-');
}

function sq(string $s): string { return "'" . str_replace(["\\", "'"], ["\\\\", "\\'"], $s) . "'"; }

$out = ["-- Generated by scripts/generate_seed.php — geography + categories seed", "SET NAMES utf8mb4;"];

// Popular countries: English-speaking list + big markets, ranked
$popCountryRank = array_flip(array_merge(['US'], $popEng));

// ---- countries ----
$vals = [];
foreach ($geo['countries'] as $c) {
    $isPop = isset($popCountryRank[$c['code']]) && $popCountryRank[$c['code']] < 12 ? 1 : 0;
    $rank  = isset($popCountryRank[$c['code']]) ? (100 - $popCountryRank[$c['code']]) : 0;
    $vals[] = sprintf('(%s,%s,%s,%d,%d)', sq($c['code']), sq($c['name']), sq($c['flag']), $isPop, $rank);
}
$out[] = 'INSERT INTO countries (code,name,flag,is_popular,popularity) VALUES ' . implode(',', $vals)
       . ' ON DUPLICATE KEY UPDATE name=VALUES(name);';

// ---- US states as regions ----
$popStates = array_flip($popular['states'] ?? []);
$vals = [];
foreach ($geo['usStates'] as $s) {
    $vals[] = sprintf("('US',%s,%s,%s,%d)", sq($s['code']), sq($s['name']), sq(slugify($s['name'])), isset($popStates[$s['code']]) ? 1 : 0);
}
$out[] = 'INSERT INTO regions (country_code,code,name,slug,is_popular) VALUES ' . implode(',', $vals)
       . ' ON DUPLICATE KEY UPDATE name=VALUES(name), is_popular=VALUES(is_popular);';

// ---- US cities (region-linked, via SELECT for region id) ----
$popCityByState = $popular['cities'] ?? [];
foreach ($cities['usCities'] as $stateCode => $cityList) {
    foreach ($cityList as $city) {
        $isPop = in_array($city, $popCityByState[$stateCode] ?? [], true) ? 1 : 0;
        $out[] = sprintf(
            "INSERT INTO cities (country_code,region_id,name,slug,is_popular)
             SELECT 'US', r.id, %s, %s, %d FROM regions r WHERE r.country_code='US' AND r.code=%s
             ON DUPLICATE KEY UPDATE is_popular=VALUES(is_popular);",
            sq($city), sq(slugify($city)), $isPop, sq($stateCode)
        );
    }
}

// ---- International cities (2-tier) ----
$vals = [];
foreach ($cities['countryCities'] as $cc => $cityList) {
    foreach ($cityList as $i => $city) {
        $vals[] = sprintf('(%s,NULL,%s,%s,%d)', sq($cc), sq($city), sq(slugify($city)), $i < 2 ? 1 : 0);
    }
}
$out[] = 'INSERT INTO cities (country_code,region_id,name,slug,is_popular) VALUES ' . implode(',', $vals)
       . ' ON DUPLICATE KEY UPDATE is_popular=VALUES(is_popular);';

// ---- categories ----
$cats = [
    ['home', 'Home & Repair', '🏠'], ['auto', 'Automotive', '🚗'],
    ['professional', 'Professional Services', '💼'], ['legal', 'Legal & Financial', '⚖️'],
    ['creative', 'Creative & Design', '🎨'], ['tech', 'Tech & AI', '🤖'],
    ['marketing', 'Marketing & Media', '📣'], ['wellness', 'Health & Wellness', '🩺'],
    ['beauty', 'Beauty & Personal Care', '💇'], ['food', 'Food & Catering', '🍽️'],
    ['events', 'Events & Entertainment', '🎉'], ['education', 'Education & Tutoring', '📚'],
    ['realestate', 'Real Estate', '🔑'], ['retail', 'Retail & Shopping', '🛍️'],
    ['pets', 'Pets & Animals', '🐾'], ['trades', 'Skilled Trades', '🔧'],
];
$vals = [];
foreach ($cats as $i => [$id, $label, $icon]) {
    $vals[] = sprintf('(%s,%s,%s,%d)', sq($id), sq($label), sq($icon), count($cats) - $i);
}
$out[] = 'INSERT INTO categories (id,label,icon,popularity) VALUES ' . implode(',', $vals)
       . ' ON DUPLICATE KEY UPDATE label=VALUES(label);';

file_put_contents(__DIR__ . '/../database/seed.sql', implode("\n", $out) . "\n");
echo "Wrote database/seed.sql (" . count($out) . " statements)\n";
